name: Build Mizofy Apps

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build_user:
    name: Build Mizofy User App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
        channel: 'stable'
    - name: Build User App
      run: |
        cd user_app
        flutter pub get
        flutter build apk --release --no-tree-shake-icons --split-per-abi
    - name: Upload User APKs
      uses: actions/upload-artifact@v4
      with:
        name: Mizofy-User-APKs
        path: user_app/build/app/outputs/flutter-apk/*.apk

  build_admin:
    name: Build Mizofy Admin App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'
        channel: 'stable'
    - name: Build Admin App
      run: |
        cd admin_app
        flutter pub get
        flutter build apk --release --no-tree-shake-icons
    - name: Upload Admin APKs
      uses: actions/upload-artifact@v4
      with:
        name: Mizofy-Admin-APKs
        path: admin_app/build/app/outputs/flutter-apk/*.apk
