name: Deploy Admin Website
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./_HIDDEN_ADMIN_/mizofy-admin
        run: npm install

      - name: Build Web App
        working-directory: ./_HIDDEN_ADMIN_/mizofy-admin
        run: npx expo export --platform web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_HIDDEN_ADMIN_/mizofy-admin/dist
